class ApiError {
  /**
   * Http status code
   */
  statusCode?: number;

  /**
   * Api transloco message for traduction
   */
  message?: string;

  /**
   * Generic message generated by the back framework
   */
  error?: string;
}

export default ApiError;
