version: "3.8"

services:

  mysql:
    image: postgres
    container_name: postges_sql
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_js:/var/lib/mysql
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - "3306:5432"

  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_started
    container_name: backend_js
    hostname: backendjs
    environment:
      - APP_PORT=7575
    ports:
      - "7575:7575"

volumes:
  db_js:
