version: "3.8"

services:

  postgres:
    restart: always
    image: postgres
    container_name: postges_sql
    hostname: database
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_js:/var/lib/mysql
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root

  backend:
    restart: always
    build:
      context: ..
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_started
    volumes:
      - ./container/keys:/srv/build/container/keys
    container_name: backend_js
    hostname: backendjs
    environment:
      - APP_PORT=7575
    ports:
      - "7575:7575"

volumes:
  db_js:
