name: Test build for backend and front

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup nodejs 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      
      - name: Install depedencies
        run: cd back &&npm ci
        
      - name: Build backend
        run: cd back && npm run build
     
      - name: Run tests
        run: cd back && npm run test
     
      - name: Run lint validity
        run: cd back && npm run lint

  build-front:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup nodejs 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      
      - name: Install depedencies
        run: cd front && npm ci
        
      - name: Build front
        run: cd front && npm run build
     
      - name: Run lint validity
        run: cd front && npm run lint
    
